# Generated by Django 5.2.9 on 2025-12-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_author_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
